import unittest
import sys
import os
import asyncio
from behave.runner_util import \
    collect_feature_locations, parse_features, \
    exec_file, load_step_modules, PathManager
sys.path.insert(0,os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))+'/src')
from behave_performance.veggie_filter import VeggieFilter
from behave_performance.helpers.paths import expand_plan_paths

class VeggieFilterTest(unittest.TestCase):
    """Test TestCaseFilter

    Args:
        unittest (_type_): _description_
    """    
    """
    Veggie Examples
    {'ast_node_ids': ['2'], 'location': {'line': 8, 'column': 1}, 'id': '20', 'tags': [{'ast_node_id': '17', 'name': '@planGerman'}, {'ast_node_id': '18', 'name': '@language'}, {'ast_node_id': '1', 'name': '@Hop'}], 'name': 'sehr einfache Simulation', 'language': 'de', 'time': None, 'total_count': None, 'total_runners': None, 'ramp_up': None, 'ramp_down': None, 'random_wait': '00:00:02', 'synchronization': None, 'groups': [{'ast_node_ids': ['0'], 'location': {'line': 9, 'column': 1}, 'id': '19', 'text': 'test.feature', 'runners': '1', 'percentage': None, 'count': '6', 'start': None, 'stop': None, 'synchronized': None}], 'uri': '..\\test\\plans\\de.plan'}
    {'ast_node_ids': ['16'], 'location': {'line': 20, 'column': 1}, 'id': '25', 'tags': [{'ast_node_id': '17', 'name': '@planGerman'}, {'ast_node_id': '18', 'name': '@language'}, {'ast_node_id': '15', 'name': '@Hop'}], 'name': 'Simulationszeitraum 2', 'language': 'de', 'time': '00:00:30', 'total_count': None, 'total_runners': None, 'ramp_up': '00:00:10', 'ramp_down': '00:00:10', 'random_wait': None, 'synchronization': None, 'groups': [{'ast_node_ids': ['5'], 'location': {'line': 21, 'column': 1}, 'id': '21', 'text': 'test.feature', 'runners': '25', 'percentage': None, 'count': None, 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'bewerten'}]}, {'cells': [{'value': 'geänderter Wert'}]}]}}}, {'ast_node_ids': ['8'], 'location': {'line': 25, 'column': 1}, 'id': '22', 'text': 'test1.feature', 'runners': '25', 'percentage': None, 'count': None, 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'Wert'}]}, {'cells': [{'value': 'geänderter Wert'}]}]}}}, {'ast_node_ids': ['11'], 'location': {'line': 29, 'column': 1}, 'id': '23', 'text': 'test2.feature', 'runners': '25', 'percentage': None, 'count': '1', 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'bewerten'}]}, {'cells': [{'value': 'geänderter Wert'}]}]}}}, {'ast_node_ids': ['14'], 'location': {'line': 35, 'column': 1}, 'id': '24', 'text': 'test3.feature', 'runners': '25', 'percentage': None, 'count': '1', 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'bewerten'}]}, {'cells': [{'value': 'geänderter Wert'}]}]}}}], 'uri': '..\\test\\plans\\de.plan'}
    {'ast_node_ids': ['2'], 'location': {'line': 8, 'column': 1}, 'id': '20', 'tags': [{'ast_node_id': '17', 'name': '@planSpanish'}, {'ast_node_id': '18', 'name': '@language'}, {'ast_node_id': '1', 'name': '@Saltar'}], 'name': 'simulación muy simple', 'language': 'es', 'time': None, 'total_count': None, 'total_runners': None, 'ramp_up': None, 'ramp_down': None, 'random_wait': '00:00:02', 'synchronization': None, 'groups': [{'ast_node_ids': ['0'], 'location': {'line': 9, 'column': 1}, 'id': '19', 'text': 'test.feature', 'runners': '1', 'percentage': None, 'count': '6', 'start': None, 'stop': None, 'synchronized': None}], 'uri': '..\\test\\plans\\es.plan'}
    {'ast_node_ids': ['16'], 'location': {'line': 20, 'column': 1}, 'id': '25', 'tags': [{'ast_node_id': '17', 'name': '@planSpanish'}, {'ast_node_id': '18', 'name': '@language'}, {'ast_node_id': '15', 'name': '@Saltar'}], 'name': 'período de simulación 2', 'language': 'es', 'time': '00:00:30', 'total_count': None, 'total_runners': None, 'ramp_up': '00:00:10', 'ramp_down': '00:00:10', 'random_wait': None, 'synchronization': None, 'groups': [{'ast_node_ids': ['5'], 'location': {'line': 21, 'column': 1}, 'id': '21', 'text': 'test.feature', 'runners': '25', 'percentage': None, 'count': None, 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'valorar'}]}, {'cells': [{'value': 'valor modificado'}]}]}}}, {'ast_node_ids': ['8'], 'location': {'line': 25, 'column': 1}, 'id': '22', 'text': 'test1.feature', 'runners': '25', 'percentage': None, 'count': None, 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'valorar'}]}, {'cells': [{'value': 'valor modificado'}]}]}}}, {'ast_node_ids': ['11'], 'location': {'line': 29, 'column': 1}, 'id': '23', 'text': 'test2.feature', 'runners': '25', 'percentage': None, 'count': '1', 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'valorar'}]}, {'cells': [{'value': 'valor modificado'}]}]}}}, {'ast_node_ids': ['14'], 'location': {'line': 35, 'column': 1}, 'id': '24', 'text': 'test3.feature', 'runners': '25', 'percentage': None, 'count': '1', 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'valorar'}]}, {'cells': [{'value': 'valor modificado'}]}]}}}], 'uri': '..\\test\\plans\\es.plan'}
    {'ast_node_ids': ['2'], 'location': {'line': 8, 'column': 1}, 'id': '20', 'tags': [{'ast_node_id': '17', 'name': '@planItalian'}, {'ast_node_id': '18', 'name': '@language'}, {'ast_node_id': '1', 'name': '@Salto'}], 'name': 'simulazione molto semplice', 'language': 'it', 'time': None, 'total_count': None, 'total_runners': None, 'ramp_up': None, 'ramp_down': None, 'random_wait': '00:00:02', 'synchronization': None, 'groups': [{'ast_node_ids': ['0'], 'location': {'line': 9, 'column': 1}, 'id': '19', 'text': 'test.feature', 'runners': '1', 'percentage': None, 'count': '6', 'start': None, 'stop': None, 'synchronized': None}], 'uri': '..\\test\\plans\\it.plan'}
    {'ast_node_ids': ['16'], 'location': {'line': 20, 'column': 1}, 'id': '25', 'tags': [{'ast_node_id': '17', 'name': '@planItalian'}, {'ast_node_id': '18', 'name': '@language'}, {'ast_node_id': '15', 'name': '@Salto'}], 'name': 'periodo di simulazione 2', 'language': 'it', 'time': '00:00:30', 'total_count': None, 'total_runners': None, 'ramp_up': '00:00:10', 'ramp_down': '00:00:10', 'random_wait': None, 'synchronization': None, 'groups': [{'ast_node_ids': ['5'], 'location': {'line': 21, 'column': 1}, 'id': '21', 'text': 'test.feature', 'runners': '25', 'percentage': None, 'count': None, 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'tasso'}]}, {'cells': [{'value': 'valore modificato'}]}]}}}, {'ast_node_ids': ['8'], 'location': {'line': 25, 'column': 1}, 'id': '22', 'text': 'test1.feature', 'runners': '25', 'percentage': None, 'count': None, 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'tasso'}]}, {'cells': [{'value': 'valore modificato'}]}]}}}, {'ast_node_ids': ['11'], 'location': {'line': 29, 'column': 1}, 'id': '23', 'text': 'test2.feature', 'runners': '25', 'percentage': None, 'count': '1', 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'tasso'}]}, {'cells': [{'value': 'valore modificato'}]}]}}}, {'ast_node_ids': ['14'], 'location': {'line': 35, 'column': 1}, 'id': '24', 'text': 'test3.feature', 'runners': '25', 'percentage': None, 'count': '1', 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'tasso'}]}, {'cells': [{'value': 'valore modificato'}]}]}}}], 'uri': '..\\test\\plans\\it.plan'}
    {'ast_node_ids': ['9'], 'location': {'line': 17, 'column': 1}, 'id': '29', 'tags': [{'ast_node_id': '25', 'name': '@planNewStyle'}, {'ast_node_id': '8', 'name': '@sample1'}], 'name': 'simulation sample', 'language': 'en', 'time': '00:00:30', 'total_count': None, 'total_runners': '10', 'ramp_up': None, 'ramp_down': None, 'random_wait': None, 'synchronization': None, 'groups': [{'ast_node_ids': ['5'], 'location': {'line': 18, 'column': 2}, 'id': '26', 'text': 'test1.feature', 'runners': None, 'percentage': '30', 'count': None, 'start': None, 'stop': None, 'synchronized': None}, {'ast_node_ids': ['6'], 'location': {'line': 20, 'column': 2}, 'id': '27', 'text': 'test2.feature', 'runners': None, 'percentage': '30', 'count': None, 'start': None, 'stop': None, 'synchronized': None}, {'ast_node_ids': ['7'], 'location': {'line': 22, 'column': 2}, 'id': '28', 'text': 'test3.feature', 'runners': None, 'percentage': '40', 'count': None, 'start': None, 'stop': None, 'synchronized': None}], 'uri': '..\\test\\plans\\new_style.plan'}
    {'ast_node_ids': ['14'], 'location': {'line': 29, 'column': 1}, 'id': '33', 'tags': [{'ast_node_id': '25', 'name': '@planNewStyle'}, {'ast_node_id': '13', 'name': '@sample2'}], 'name': 'simulation sample 2', 'language': 'en', 'time': '00:00:30', 'total_count': None, 'total_runners': '10', 'ramp_up': '00:00:10', 'ramp_down': '00:00:10', 'random_wait': '00:00:02', 'synchronization': None, 'groups': [{'ast_node_ids': ['10'], 'location': {'line': 30, 'column': 2}, 'id': '30', 'text': 'test1.feature', 'runners': None, 'percentage': None, 'count': None, 'start': None, 'stop': None, 'synchronized': None}, {'ast_node_ids': ['11'], 'location': {'line': 31, 'column': 2}, 'id': '31', 'text': 'test2.feature', 'runners': None, 'percentage': '30', 'count': None, 'start': None, 'stop': None, 'synchronized': None}, {'ast_node_ids': ['12'], 'location': {'line': 33, 'column': 2}, 'id': '32', 'text': 'test3.feature', 'runners': None, 'percentage': '40', 'count': None, 'start': None, 'stop': None, 'synchronized': None}], 'uri': '..\\test\\plans\\new_style.plan'}
    {'ast_node_ids': ['19'], 'location': {'line': 43, 'column': 1}, 'id': '37', 'tags': [{'ast_node_id': '25', 'name': '@planNewStyle'}, {'ast_node_id': '18', 'name': '@sample3'}], 'name': 'simulation ex sample example', 'language': 'en', 'time': None, 'total_count': '100', 'total_runners': '10', 'ramp_up': '00:00:10', 'ramp_down': '00:00:10', 'random_wait': None, 'synchronization': None, 'groups': [{'ast_node_ids': ['15'], 'location': {'line': 44, 'column': 2}, 'id': '34', 'text': 'test1.feature', 'runners': None, 'percentage': '33', 'count': None, 'start': None, 'stop': None, 'synchronized': None}, {'ast_node_ids': ['16'], 'location': {'line': 46, 'column': 2}, 'id': '35', 'text': 'test2.feature', 'runners': None, 'percentage': '33', 'count': None, 'start': None, 'stop': None, 'synchronized': None}, {'ast_node_ids': ['17'], 'location': {'line': 48, 'column': 2}, 'id': '36', 'text': 'test3.feature', 'runners': None, 'percentage': '33', 'count': None, 'start': None, 'stop': None, 'synchronized': None}], 'uri': '..\\test\\plans\\new_style.plan'}
    {'ast_node_ids': ['24'], 'location': {'line': 62, 'column': 1}, 'id': '41', 'tags': [{'ast_node_id': '25', 'name': '@planNewStyle'}, {'ast_node_id': '23', 'name': '@sample4'}], 'name': '4 sample 4', 'language': 'en', 'time': '00:00:30', 'total_count': None, 'total_runners': '30', 'ramp_up': '00:00:10', 'ramp_down': '00:00:10', 'random_wait': None, 'synchronization': None, 'groups': [{'ast_node_ids': ['20'], 'location': {'line': 63, 'column': 2}, 'id': '38', 'text': 'test1.feature', 'runners': None, 'percentage': '30', 'count': None, 'start': None, 'stop': None, 'synchronized': None}, {'ast_node_ids': ['21'], 'location': {'line': 65, 'column': 2}, 'id': '39', 'text': 'test2.feature', 'runners': None, 'percentage': '30', 'count': None, 'start': None, 'stop': None, 'synchronized': None}, {'ast_node_ids': ['22'], 'location': {'line': 67, 'column': 2}, 'id': '40', 'text': 'test3.feature', 'runners': None, 'percentage': '40', 'count': None, 'start': None, 'stop': None, 'synchronized': None}], 'uri': '..\\test\\plans\\new_style.plan'}
    {'ast_node_ids': ['2'], 'location': {'line': 7, 'column': 1}, 'id': '65', 'tags': [{'ast_node_id': '62', 'name': '@planNegTest'}, {'ast_node_id': '63', 'name': '@planPosTest'}, {'ast_node_id': '1', 'name': '@deadsimple'}], 'name': 'simulation deadsimple', 'language': 'en', 'time': None, 'total_count': None, 'total_runners': None, 'ramp_up': None, 'ramp_down': None, 'random_wait': '00:00:02', 'synchronization': None, 'groups': [{'ast_node_ids': ['0'], 'location': {'line': 8, 'column': 1}, 'id': '64', 'text': 'test.feature', 'runners': '1', 'percentage': None, 'count': '6', 'start': None, 'stop': None, 'synchronized': None}], 'uri': '..\\test\\plans\\test.plan'}    
    {'ast_node_ids': ['6'], 'location': {'line': 19, 'column': 1}, 'id': '68', 'tags': [{'ast_node_id': '62', 'name': '@planNegTest'}, {'ast_node_id': '63', 'name': '@planPosTest'}, {'ast_node_id': '5', 'name': '@simple'}], 'name': 'simulation simple', 'language': 'en', 'time': None, 'total_count': None, 'total_runners': None, 'ramp_up': None, 'ramp_down': None, 'random_wait': '00:00:02', 'synchronization': None, 'groups': [{'ast_node_ids': ['3'], 'location': {'line': 20, 'column': 1}, 'id': '66', 'text': 'test.feature', 'runners': '2', 'percentage': None, 'count': '2', 'start': None, 'stop': None, 'synchronized': None}, {'ast_node_ids': ['4'], 'location': {'line': 25, 'column': 1}, 'id': '67', 'text': 'test1.feature', 'runners': '2', 'percentage': None, 'count': '2', 'start': None, 'stop': None, 'synchronized': None}], 'uri': '..\\test\\plans\\test.plan'}
    {'ast_node_ids': ['18'], 'location': {'line': 38, 'column': 1}, 'id': '71', 'tags': [{'ast_node_id': '62', 'name': '@planNegTest'}, {'ast_node_id': '63', 'name': '@planPosTest'}, {'ast_node_id': '15', 'name': '@simPos'}, {'ast_node_id': '16', 'name': '@tskip'}, {'ast_node_id': '17', 'name': '@slice_1'}], 'name': 'simulation 1 slices', 'language': 'en', 'time': None, 'total_count': None, 'total_runners': None, 'ramp_up': None, 'ramp_down': None, 'random_wait': '00:00:02', 'synchronization': None, 'groups': [{'ast_node_ids': ['10'], 'location': {'line': 39, 'column': 1}, 'id': '69', 'text': '@only1,@only2', 'runners': '2', 'percentage': None, 'count': '1', 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'value out'}]}, {'cells': [{'value': 'changed value 1'}]}, {'cells': [{'value': 'changed value 2'}]}]}}}, {'ast_node_ids': ['14'], 'location': {'line': 47, 'column': 1}, 'id': '70', 'text': 'test.feature', 'runners': '2', 'percentage': None, 'count': '2', 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'value out'}]}, {'cells': [{'value': 'changed value 3'}]}, {'cells': [{'value': 'changed value 4'}]}]}}}], 'uri': '..\\test\\plans\\test.plan'}
    {'ast_node_ids': ['29'], 'location': {'line': 64, 'column': 1}, 'id': '74', 'tags': [{'ast_node_id': '62', 'name': '@planNegTest'}, {'ast_node_id': '63', 'name': '@planPosTest'}, {'ast_node_id': '27', 'name': '@bskip'}, {'ast_node_id': '28', 'name': '@tskip'}], 'name': 'simulation 1 skip', 'language': 'en', 'time': None, 'total_count': None, 'total_runners': None, 'ramp_up': None, 'ramp_down': None, 'random_wait': None, 'synchronization': None, 'groups': [{'ast_node_ids': ['22'], 'location': {'line': 65, 'column': 1}, 'id': '72', 'text': 'test.feature', 'runners': '2', 'percentage': None, 'count': '2', 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'value out'}]}, {'cells': [{'value': 'changed value 1'}]}, {'cells': [{'value': 'changed value 2'}]}]}}}, {'ast_node_ids': ['26'], 'location': {'line': 73, 'column': 2}, 'id': '73', 'text': 'test.feature', 'runners': '2', 'percentage': None, 'count': '2', 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'value out'}]}, {'cells': [{'value': 'changed value 3'}]}, {'cells': [{'value': 'changed value 4'}]}]}}}], 'uri': '..\\test\\plans\\test.plan'}     
    {'ast_node_ids': ['33'], 'location': {'line': 84, 'column': 1}, 'id': '76', 'tags': [{'ast_node_id': '62', 'name': '@planNegTest'}, {'ast_node_id': '63', 'name': '@planPosTest'}, {'ast_node_id': '31', 'name': '@bskip'}, {'ast_node_id': '32', 'name': '@outputtest'}], 'name': 'simulation test', 'language': 'en', 'time': None, 'total_count': None, 'total_runners': None, 'ramp_up': None, 'ramp_down': None, 'random_wait': None, 'synchronization': None, 'groups': [{'ast_node_ids': ['30'], 'location': {'line': 85, 'column': 2}, 'id': '75', 'text': 'test.feature', 'runners': '3', 'percentage': None, 'count': '6', 'start': None, 'stop': None, 'synchronized': None}], 'uri': '..\\test\\plans\\test.plan'}
    {'ast_node_ids': ['48'], 'location': {'line': 93, 'column': 1}, 'id': '81', 'tags': [{'ast_node_id': '62', 'name': '@planNegTest'}, {'ast_node_id': '63', 'name': '@planPosTest'}, {'ast_node_id': '46', 'name': '@tskip'}, {'ast_node_id': '47', 'name': '@simperiodtest'}], 'name': 'simulation 2 period', 'language': 'en', 'time': '00:00:30', 'total_count': None, 'total_runners': None, 'ramp_up': '00:00:10', 'ramp_down': '00:00:10', 'random_wait': None, 'synchronization': None, 'groups': [{'ast_node_ids': ['36'], 'location': {'line': 94, 'column': 1}, 'id': '77', 'text': 'test.feature', 'runners': '50', 'percentage': None, 'count': None, 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'value out'}]}, {'cells': [{'value': 'changed value'}]}]}}}, {'ast_node_ids': ['39'], 'location': {'line': 98, 'column': 1}, 'id': '78', 'text': 'test1.feature', 'runners': '50', 'percentage': None, 'count': None, 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'value out'}]}, {'cells': [{'value': 'changed value'}]}]}}}, {'ast_node_ids': ['42'], 'location': {'line': 102, 'column': 1}, 'id': '79', 'text': 'test2.feature', 'runners': '50', 'percentage': None, 'count': '1', 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'value out'}]}, {'cells': [{'value': 'changed value'}]}]}}}, {'ast_node_ids': ['45'], 'location': {'line': 108, 'column': 1}, 'id': '80', 'text': 'test3.feature', 'runners': '50', 'percentage': None, 'count': '1', 'start': None, 'stop': None, 'synchronized': None, 'argument': {'data_table': {'rows': [{'cells': [{'value': 'value out'}]}, {'cells': [{'value': 'changed value'}]}]}}}], 'uri': '..\\test\\plans\\test.plan'}
    {'ast_node_ids': ['55'], 'location': {'line': 123, 'column': 1}, 'id': '84', 'tags': [{'ast_node_id': '62', 'name': '@planNegTest'}, {'ast_node_id': '63', 'name': '@planPosTest'}, {'ast_node_id': '53', 'name': '@tskip'}, {'ast_node_id': '54', 'name': '@simperiod3testfail'}], 'name': 'simulation 3 period', 'language': 'en', 'time': '00:00:30', 'total_count': None, 'total_runners': None, 'ramp_up': None, 'ramp_down': '00:00:10', 'random_wait': None, 'synchronization': None, 'groups': [{'ast_node_ids': ['49'], 'location': {'line': 124, 'column': 1}, 'id': '82', 'text': 'test.feature', 'runners': None, 'percentage': None, 'count': None, 'start': None, 'stop': None, 'synchronized': None}, {'ast_node_ids': ['52'], 'location': {'line': 125, 'column': 1}, 'id': '83', 'text': 'test3
    """

    def setUp(self) -> None:
        self.plans = expand_plan_paths(os.path.realpath('.\\test\\plans'))

    def test_veggie_filter_init(self):
        try:
            vf = VeggieFilter(self.plans,['name'],['@tag'])
        except Exception:
            self.assertTrue(False)
    
    def test_veggie_filter_matches_tag_simulation(self):
        try:
            vf = VeggieFilter(self.plans,['name'],['@simple'])
            result = vf.matches_all_tag_expressions({'ast_node_ids': ['6'], 'location': {'line': 19, 'column': 1}, 'id': '68', 'tags': [{'ast_node_id': '62', 'name': '@planNegTest'}, {'ast_node_id': '63', 'name': '@planPosTest'}, {'ast_node_id': '5', 'name': '@simple'}], 'name': 'simulation simple', 'language': 'en', 'time': None, 'total_count': None, 'total_runners': None, 'ramp_up': None, 'ramp_down': None, 'random_wait': '00:00:02', 'synchronization': None, 'groups': [{'ast_node_ids': ['3'], 'location': {'line': 20, 'column': 1}, 'id': '66', 'text': 'test.feature', 'runners': '2', 'percentage': None, 'count': '2', 'start': None, 'stop': None, 'synchronized': None}, {'ast_node_ids': ['4'], 'location': {'line': 25, 'column': 1}, 'id': '67', 'text': 'test1.feature', 'runners': '2', 'percentage': None, 'count': '2', 'start': None, 'stop': None, 'synchronized': None}], 'uri': '..\\test\\plans\\test.plan'})
            self.assertTrue(result)
        except Exception:
            self.assertTrue(False)
    
    def test_veggie_filter_matches_tag_plan(self):
        try:
            vf = VeggieFilter(self.plans,['name'],['@planPosTest'])
            result = vf.matches_all_tag_expressions({'ast_node_ids': ['6'], 'location': {'line': 19, 'column': 1}, 'id': '68', 'tags': [{'ast_node_id': '62', 'name': '@planNegTest'}, {'ast_node_id': '63', 'name': '@planPosTest'}, {'ast_node_id': '5', 'name': '@simple'}], 'name': 'simulation simple', 'language': 'en', 'time': None, 'total_count': None, 'total_runners': None, 'ramp_up': None, 'ramp_down': None, 'random_wait': '00:00:02', 'synchronization': None, 'groups': [{'ast_node_ids': ['3'], 'location': {'line': 20, 'column': 1}, 'id': '66', 'text': 'test.feature', 'runners': '2', 'percentage': None, 'count': '2', 'start': None, 'stop': None, 'synchronized': None}, {'ast_node_ids': ['4'], 'location': {'line': 25, 'column': 1}, 'id': '67', 'text': 'test1.feature', 'runners': '2', 'percentage': None, 'count': '2', 'start': None, 'stop': None, 'synchronized': None}], 'uri': '..\\test\\plans\\test.plan'})
            self.assertTrue(result)
        except Exception:
            self.assertTrue(False)
    
    def test_veggie_filter_matches_name(self):
        try:
            vf = VeggieFilter(self.plans,['simulation simple'])
            result = vf.matches_any_name({'ast_node_ids': ['6'], 'location': {'line': 19, 'column': 1}, 'id': '68', 'tags': [{'ast_node_id': '62', 'name': '@planNegTest'}, {'ast_node_id': '63', 'name': '@planPosTest'}, {'ast_node_id': '5', 'name': '@simple'}], 'name': 'simulation simple', 'language': 'en', 'time': None, 'total_count': None, 'total_runners': None, 'ramp_up': None, 'ramp_down': None, 'random_wait': '00:00:02', 'synchronization': None, 'groups': [{'ast_node_ids': ['3'], 'location': {'line': 20, 'column': 1}, 'id': '66', 'text': 'test.feature', 'runners': '2', 'percentage': None, 'count': '2', 'start': None, 'stop': None, 'synchronized': None}, {'ast_node_ids': ['4'], 'location': {'line': 25, 'column': 1}, 'id': '67', 'text': 'test1.feature', 'runners': '2', 'percentage': None, 'count': '2', 'start': None, 'stop': None, 'synchronized': None}], 'uri': '..\\test\\plans\\test.plan'})
            self.assertTrue(result)
        except Exception:
            self.assertTrue(False)

    def test_veggie_filter_matches_location(self):
        try:
            vf = VeggieFilter(['./test/plans/test.plan:19'])
            result = vf.matches_any_line({'ast_node_ids': ['6'], 'location': {'line': 19, 'column': 1}, 'id': '68', 'tags': [{'ast_node_id': '62', 'name': '@planNegTest'}, {'ast_node_id': '63', 'name': '@planPosTest'}, {'ast_node_id': '5', 'name': '@simple'}], 'name': 'simulation simple', 'language': 'en', 'time': None, 'total_count': None, 'total_runners': None, 'ramp_up': None, 'ramp_down': None, 'random_wait': '00:00:02', 'synchronization': None, 'groups': [{'ast_node_ids': ['3'], 'location': {'line': 20, 'column': 1}, 'id': '66', 'text': 'test.feature', 'runners': '2', 'percentage': None, 'count': '2', 'start': None, 'stop': None, 'synchronized': None}, {'ast_node_ids': ['4'], 'location': {'line': 25, 'column': 1}, 'id': '67', 'text': 'test1.feature', 'runners': '2', 'percentage': None, 'count': '2', 'start': None, 'stop': None, 'synchronized': None}], 'uri': '.\\test\\plans\\test.plan'},'.\\test\\plans\\test.plan')
            self.assertTrue(result)
        except Exception:
            self.assertTrue(False)

if __name__ == '__main__':
    unittest.main()